# Generated by Django 5.1.6 on 2025-02-28 10:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-admission_date'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AddField(
            model_name='patient',
            name='bills_documents',
            field=models.FileField(blank=True, null=True, upload_to='bills/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Bills and Documents'),
        ),
        migrations.AddField(
            model_name='patient',
            name='case_file',
            field=models.FileField(blank=True, null=True, upload_to='case_files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])], verbose_name='Case File'),
        ),
        migrations.AddField(
            model_name='patient',
            name='case_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='deviations',
            field=models.JSONField(default=list, help_text='List of deviations found'),
        ),
        migrations.AddField(
            model_name='patient',
            name='digital_signature',
            field=models.TextField(blank=True, null=True, verbose_name='Digital Signature'),
        ),
        migrations.AddField(
            model_name='patient',
            name='discharge_summary',
            field=models.FileField(blank=True, null=True, upload_to='discharge_summaries/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='package_code',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Patient Photo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='total_oope',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Out of Pocket Expenses'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='case_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Case ID / IP Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='missing_records',
            field=models.BooleanField(default=False, verbose_name='Mandatory Records'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='money_collection',
            field=models.BooleanField(default=False, verbose_name='Money Collection'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordinator',
                'verbose_name_plural': 'Coordinators',
                'ordering': ['name'],
                'permissions': [('view_district_data', 'Can view district data'), ('edit_district_data', 'Can edit district data')],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('AUDIT', 'Audit Performed'), ('PATIENT_UPDATE', 'Patient Details Updated'), ('RECORD_CHECK', 'Records Checked'), ('MONEY_VERIFY', 'Money Status Verified'), ('OTHER', 'Other Action')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.district')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit.patient')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.coordinator')),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FieldAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=50)),
                ('ehcp_name', models.CharField(max_length=200)),
                ('ehcp_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=10)),
                ('auditor_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('current_location', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ekgp_patients', models.IntegerField(default=0)),
                ('pmjay_patients', models.IntegerField(default=0)),
                ('beneficiaries', models.IntegerField(default=0)),
                ('findings_type', models.CharField(blank=True, choices=[('audit_findings', 'AUDIT FINDINGS'), ('hnqa_related', 'HNQA RELATED'), ('other_fraudulent_activities', 'ANY OTHER FRAUDULENT ACTIVITIES')], default=None, max_length=50, null=True)),
                ('audit_findings_value', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('finding_type', models.CharField(blank=True, max_length=50, null=True)),
                ('abuse_type', models.CharField(blank=True, max_length=50, null=True)),
                ('oope_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hnqa_value', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('hnqa_type', models.CharField(blank=True, max_length=50, null=True)),
                ('infrastructure_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hr_type', models.CharField(blank=True, max_length=50, null=True)),
                ('services_type', models.CharField(blank=True, max_length=50, null=True)),
                ('fraudulent_value', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('fraudulent_type', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('infrastructure_score', models.IntegerField(default=0)),
                ('service_score', models.IntegerField(default=0)),
                ('documentation_score', models.IntegerField(default=0)),
                ('feedback_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audit.district')),
            ],
            options={
                'ordering': ['-visit_date', 'ehcp_name'],
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='audit.fieldaudit'),
        ),
        migrations.DeleteModel(
            name='EHCPAudit',
        ),
    ]
